app <- ShinyDriver$new("../", seed = 5)
app$snapshotInit("loaddata_switchtaxon_realdata_multisampletab_switchcharacteristic_switchtaxon_mixnodatarealdata_switchtaxon_nodata")

app$setInputs(select_dir = "/home/fellows/Documents/Scripts/shiny_web_apps/MEx-IPA/dev/test_data/maltExtract_v1.5_Weyrich2017Velsko2019")
app$setInputs(submit = "click")
app$snapshot()
app$setInputs(`selected_node-selectized` = "freti")
app$setInputs(selected_node = "Fretibacterium_fastidiosum")
app$setInputs(outae5ee68dc366b145_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(outae5ee68dc366b145_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17), allowInputNoBinding_ = TRUE)
app$snapshot()
app$snapshot()
app$setInputs(characteristic = "length")
app$snapshot()
app$setInputs(characteristic = "edit")
app$snapshot()
app$setInputs(characteristic = "percentidentity")
app$snapshot()
app$setInputs(characteristic = "positionscovered")
app$snapshot()
app$setInputs(characteristic = "coveragehist")
app$snapshot()
app$setInputs(`selected_node-selectized` = "cer")
app$setInputs(selected_node = "Ceratotherium_simum_simum")
app$snapshot()
app$snapshot()
app$setInputs(selected_node = "Coprinopsis_cinerea_okayama7#130")
app$setInputs(selected_node = "Methanobrevibacter_smithii_ATCC_35061")
