app <- ShinyDriver$new("../", seed = 5)
app$snapshotInit("loaddata_switchsample_realdata_switchinteractive")

app$setInputs(select_dir = "/home/fellows/Documents/Scripts/shiny_web_apps/MEx-IPA/dev/test_data/maltExtract_v1.5_Weyrich2017Velsko2019")
app$setInputs(submit = "click")
app$setInputs(`selected_node-selectized` = "Fre")
app$setInputs(selected_node = "Fretibacterium_fastidiosum")
app$setInputs(outc78191ad5bb111e1_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(outc78191ad5bb111e1_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17), allowInputNoBinding_ = TRUE)
app$snapshot()
app$setInputs(interactive = TRUE)
app$snapshot()
app$setInputs(interactive = FALSE)
app$snapshot()
